// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPP2NOD8o1Q2J1eZY_hhA89TQ8mr7W9Ag',
    appId: '1:3430677960:web:93db6de76ab9034e2494fd',
    messagingSenderId: '3430677960',
    projectId: 'final-project-6d299',
    authDomain: 'final-project-6d299.firebaseapp.com',
    storageBucket: 'final-project-6d299.firebasestorage.app',
    measurementId: 'G-86XC5B1Q6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0z5VkfeV6_FP7KK7q32hQMGupNXn00r0',
    appId: '1:3430677960:android:f38e3fe7462b07922494fd',
    messagingSenderId: '3430677960',
    projectId: 'final-project-6d299',
    storageBucket: 'final-project-6d299.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPP2NOD8o1Q2J1eZY_hhA89TQ8mr7W9Ag',
    appId: '1:3430677960:web:a4a03d57b3583e1a2494fd',
    messagingSenderId: '3430677960',
    projectId: 'final-project-6d299',
    authDomain: 'final-project-6d299.firebaseapp.com',
    storageBucket: 'final-project-6d299.firebasestorage.app',
    measurementId: 'G-WHYRD19R7H',
  );
}
